// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearChangeLog():Promise<void>;

export function ClearMonitoringData():Promise<void>;

export function FetchNow():Promise<void>;

export function GetChangeLog():Promise<Array<main.ChangeLogEntry>>;

export function GetConfig():Promise<main.Config>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetMonitoringStatus():Promise<boolean>;

export function GetStats():Promise<main.Stats>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function TestNotification():Promise<void>;
