// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChangeLog() {
  return window['go']['main']['App']['ClearChangeLog']();
}

export function ClearMonitoringData() {
  return window['go']['main']['App']['ClearMonitoringData']();
}

export function FetchNow() {
  return window['go']['main']['App']['FetchNow']();
}

export function GetChangeLog() {
  return window['go']['main']['App']['GetChangeLog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OpenURLInChrome(arg1) {
  return window['go']['main']['App']['OpenURLInChrome'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestNotification() {
  return window['go']['main']['App']['TestNotification']();
}
